# Build and deploy Irked
stages:
 - prep
 - build
 - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/

get-repo:
 stage: prep
 image: python
 only:
  - master
  - tags
 script:
  - pip install awscli
  - aws s3 sync s3://cloudonix-dist/maven2/releases/tech/greenfield/irked-vertx/maven-metadata.xml maven-repo/releases/tech/greenfield/irked-vertx/maven-metadata.xml
 artifacts:
  paths:
   - maven-repo/*

package:
 stage: build
 image: maven:3-jdk-11
 script:
  - mkdir -p .m2 && cp m2-settings.xml .m2/settings.xml
  - mvn -B package
  - base64 -d <<<${GPG_PRIVATE_KEY} | gpg --import
  - mvn -DskipTests -DaltDeploymentRepository=repo::default::file:./maven-repo/$(grep -q SNAPSHOT pom.xml && echo snapshots || echo releases) deploy
  - mvn -DskipTests deploy -DrepositoryId=ossrh
    -Dgpg.keyname=${GPG_KEYNAME} -Dgpg.passphrase="$(base64 -d <<<${GPG_PASSPHRASE})"
    -Drepository.username=${REPO_USERNAME} -Drepository.password="$(base64 -d <<<${REPO_PASSWORD})" || true
 artifacts:
  paths:
   - maven-repo/*
   - target/*

s3:
 stage: deploy
 image: python
 only:
  - master
  - tags
 script:
  - pip install awscli
  - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read maven-repo/ s3://cloudonix-dist/maven2/
