# Build and deploy Irked
stages:
 - prep
 - build
 - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/

get-repo:
 stage: prep
 image: python
 only:
  - master
  - tags
 script:
  - pip install awscli
  - aws s3 cp s3://cloudonix-dist/maven2/releases/tech/greenfield/irked-vertx/maven-metadata.xml maven-repo/releases/tech/greenfield/irked-vertx/maven-metadata.xml
 artifacts:
  paths:
   - maven-repo/*

package:
 stage: build
 image: maven:3-jdk-11
 script:
  - mvn -s m2-settings.xml -B package
  - mvn -s m2-settings.xml -B -DskipTests -DaltDeploymentRepository=repo::default::file:./maven-repo/$(grep -q SNAPSHOT pom.xml && echo snapshots || echo releases) deploy
 artifacts:
  paths:
   - maven-repo/*
   - target/*

ossrh:
 stage: deploy
 image: maven:3-jdk-11
 only:
  - tags
 script:
  - base64 -d <<<${GPG_PRIVATE_KEY} | gpg --import --batch
  - mvn -s m2-settings.xml -B -DskipTests package gpg:sign
    -Dmaven.gpg.skip=false -Dgpg.keyname=${GPG_KEYNAME} -Dgpg.passphrase="$(base64 -d <<<${GPG_PASSPHRASE})"
  - mvn -s m2-settings.xml -B -DskipTests deploy
    -DrepositoryId=ossrh -Drepository.username=${OSSRH_USERNAME} -Drepository.password="${OSSRH_PASSWORD}"

s3:
 stage: deploy
 image: python
 script:
  - pip install awscli
  - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read maven-repo/ s3://cloudonix-dist/maven2/
