# Build and deploy Irked
stages:
 - build
 - deploy

package:
 stage: build
 image: maven
 script:
  - mvn -B package
  - mvn -DaltDeploymentRepository=repo::default::file:./maven-repo/releases deploy
 artifacts:
  paths:
   - maven-repo/*
   - target/*

packagecloud-snapshot:
 stage: deploy
 image: maven
 except:
  - master
 script:
  - apt-get update && apt-get install -qy xmlstarlet
  - mkdir -p $HOME/.m2
  - echo "<settings><servers><server><id>packagecloud-GreenfieldTech</id><password>$PC_TOKEN</password></server></servers></settings>" > $HOME/.m2/settings.xml
#  - export VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.2:evaluate -Dexpression=project.version | grep -Ev '(^\[|Download\w+:))
  - export VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
  - xmlstarlet ed -P -L -O -N p=http://maven.apache.org/POM/4.0.0 -u '/p:project/p:version' -v $VERSION-SNAPSHOT pom.xml
  - mvn deploy

packagecloud:
 stage: deploy
 image: maven
 only:
  - master
 script:
  - mkdir -p $HOME/.m2
  - echo "<settings><servers><server><id>packagecloud-GreenfieldTech</id><password>$PC_TOKEN</password></server></servers></settings>" > $HOME/.m2/settings.xml
  - mvn deploy

s3:
 stage: deploy
 image: python
 only:
  - master
 script:
  - pip install awscli
  - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read maven-repo/ s3://cloudonix-dist/maven2/
