# Build and deploy Irked
stages:
 - prep
 - build
 - deploy

get-repo:
  stage: prep
  image: python
 only:
  - master
  - tags
 script:
  - pip install awscli
  - aws s3 sync s3://cloudonix-dist/maven2/releases/tech/greenfield/irked-vertx/  maven-repo/releases/tech/greenfield/irked-vertx/

package:
 stage: build
 image: maven:3-jdk-11
 script:
  - mvn -B package
  - mvn -DaltDeploymentRepository=repo::default::file:./maven-repo/$(grep -q SNAPSHOT pom.xml && echo snapshots || echo releases) deploy
 artifacts:
  paths:
   - maven-repo/*
   - target/*

s3:
 stage: deploy
 image: python
 only:
  - master
  - tags
 script:
  - pip install awscli
  - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read maven-repo/ s3://cloudonix-dist/maven2/
