# Build and deploy Irked
stages:
 - prep
 - build
 - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

image: maven:3-jdk-11

cache:
  paths:
    - .m2/

get-repo:
 stage: prep
 image: python
 only:
  - master
  - tags
 script:
  - pip install awscli
  - aws s3 cp s3://cloudonix-dist/maven2/releases/tech/greenfield/irked-vertx/maven-metadata.xml maven-repo/releases/tech/greenfield/irked-vertx/maven-metadata.xml
 artifacts:
  paths:
   - maven-repo/*

package:
 stage: build
 script:
  - mvn -s m2-settings.xml -B package
  - mvn -s m2-settings.xml -B -DskipTests -DaltDeploymentRepository=repo::default::file:./maven-repo/$(grep -q SNAPSHOT pom.xml && echo snapshots || echo releases) deploy
 artifacts:
  paths:
   - maven-repo/*
   - target/*

maven-repo:
 stage: build
 needs: [ package ]
 script:
  mvn -s ci-settings.xml -DskipTests -Dmaven.gpg.skip=true deploy -Pgitlab-maven
 rules:
  - if: $CI_COMMIT_TAG

ossrh:
 stage: deploy
 only:
  - tags
 script:
  - export SIGN_KEY_ID=$GPG_KEYNAME
  - export SIGN_KEY_PASS="$(base64 -d <<<$GPG_PASSPHRASE)"
  - export SIGN_KEY="$(base64 -d <<<"$GPG_PRIVATE_KEY"| gpg --import && gpg --export-secret-keys --armor)"
  - mvn -s m2-settings.xml -B -DskipTests package sign:sign deploy -Dsign.skip=false -DrepositoryId=ossrh -Drepository.username=${OSSRH_USERNAME} -Drepository.password="${OSSRH_PASSWORD}"

s3:
 stage: deploy
 image: python
 script:
  - pip install awscli
  - aws s3 sync --storage-class REDUCED_REDUNDANCY --acl public-read maven-repo/ s3://cloudonix-dist/maven2/
